services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
    # Weather API Environment Variables
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - TARGET_CITY=${TARGET_CITY}
      - FORECAST_DAYS=${FORECAST_DAYS}
    # PostgreSQL Database Environment Variables
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${PG_DB}           
      POSTGRES_USER: ${PG_USER}       
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  db_data: