services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - TARGET_CITY=${TARGET_CITY}
      - FORECAST_DAYS=${FORECAST_DAYS}
    command: python main.py